---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/figure_2_income/figure_2_income.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/176950/articles/213251/master/file/figures/figure_2_income/figure_2_income.png"
    folder_url: "/users/176950/articles/213251/master/folder/figures/figure_2_income"
